#!/bin/bash
# configure ruby mbariRuby build for arm-linux -- 10/22/23 brent@mbari.org
# for gcc x86 add:
# -fno-stack-protector
# to CFLAGS
# Also note that gcc >=4.7 requires -fno-tree-dce
# gcc version >= 10 targeting i386 requires STACK_WIPE_SITES 0x4xxx
# otherwise produces broken binaries at -O2 or higher 
: ${CFLAGS:="-O2 -g"}
: ${rubyCC:=gcc}
: ${rubyCFLAGS:="-Os -g"}
[ "$MBARIcflags" ] && CFLAGS="$CFLAGS $MBARIcflags"
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${ARMPREFIX:=$ARMGCC/usr}
: ${ARMHOST:=arm-softfloat-linux}
: ${CC:=$ARMGCC/bin/gcc}
: ${TARGETTOP:=${1-/opt/mbari}}
for mod in mbarilib termios .; do
  [ -r $mod/Makefile ] && make -C $mod MINIRUBY=miniruby distclean
done

read gcc version fullVersion extra <<< "$($CC -v 2>&1 | tail -1)" || exit
IFS=. read gccMajor gccMinor gccExtra <<< "$fullVersion"
unset IFS

[ $gccMajor -ge 4 ] && CFLAGS="$CFLAGS -fno-stack-protector -fno-tree-dce"
 
[ ${wipeSites+x} ] || {
  wipeSites=0x8770
  [ $gccMajor -gt 9 ] && wipeSites=0x4770
}
[ "$wipeSites" ] && CFLAGS="$CFLAGS -DSTACK_WIPE_SITES=$wipeSites"

export CFLAGS CXXFLAGS

rm -f config.cache configure ext/readline/libreadline.so*
autoconf || exit $?
if [ ! -x miniruby ]; then
  configure --enable-mbari-api &&
  echo Building miniruby for this host
  rm -f *.o && make -j4 CC=$rubyCC CFLAGS="$rubyCFLAGS" miniruby || {
    echo "could not build miniruby"
    exit 8
  }
  rm *.o
fi
echo Reconfiguring RUBY build for $ARMHOST
export CC
rb_cv_stack_grow_dir=-1 ac_cv_func_memcmp_working=yes \
ac_cv_func_getpgrp_void=yes ac_cv_func_setpgrp_void=yes \
rb_cv_need_io_seek_between_rw=no \
LDFLAGS=-L${ARMPREFIX}/lib \
CPPFLAGS=-I${ARMPREFIX}/include \
RPATHFLAG=" -Wl,-R$TARGETTOP/lib" \
configure --disable-option-checking --disable-rpath \
   --host=$ARMHOST --prefix=$TARGETTOP --disable-ipv6 --without-X11 \
   --enable-mbari-api --disable-pthread --disable-ucontext $@ ||
 exit 2
echo 'Patching RUBY_*_LIB* in config.h for target'
sed -e "s:\"$ARMPREFIX:\"$TARGETTOP:g" config.h >config.h.patched || {
  echo "Failed to patch config.h"
  exit 3
}
#collect the trash more often
echo "#define GC_MALLOC_LIMIT 2000000" >> config.h.patched
mv -f config.h.patched config.h || exit 6

echo 'Patching Makefile for cross compilation'
sed -e "s:MINIRUBY = ruby:MINIRUBY = $PWD/miniruby:1" \
        Makefile >Makefile.patched || {
  echo "Failed to patch Makefile"
  exit 3
}
mv -f Makefile.patched Makefile

  echo "  $ arminstall       #to install ruby and core libaries"
