#!/bin/bash
#Build and optionally install the extra ruby utilities MBARI needs for ESP
#parameters are passed on to make
#to force complete rebuild:  buildUtils clean all
#to install for an arm host, force our ruby to load a different rbconfig.rb:
# RUBYLIB=~/armHost/usr/local/lib/ruby/1.6/arm-linux buildUtils clean install

toolDirs='mbarilib termios'
defdir=`dirname $0`
case $defdir in
  /*) ;;
  *)  defdir=$PWD/$defdir ;;
esac
: ${RUBY:="$defdir/miniruby -I$defdir -I$defdir/lib"}
for d in $toolDirs; do
  cd $d && {
    for mktarget; do
      [ "$mktarget" = clean ] && {
        echo "Making $d:"
        $RUBY extconf.rb || exit $?
      }
    done
    make "$@" || exit 1
    cd ..
  }
done
for mktarget; do  #for things that don't have an explicit "build" operation
  [ "$mktarget" = install ] && {
    echo "Installing MBARI core Ruby libraries..."
    $RUBY inst-mbari.rb $DESTDIR || exit 32
    break
  }
done
:
