#!/bin/bash
# configure ESP MBARI Ruby build for workstation -- 11/22/21 brent@mbari.org
# for gcc x86 add:
#  -fno-stack-protector
# to CFLAGS
# Also note that gcc >=4.7 requires -fno-tree-dce
# gcc version >= 10 targeting i386 requires STACK_WIPE_SITES 0x4xxx
# otherwise produces broken binaries at -O2 or higher 
# Use:
#   espconfig CC=gcc-9  #unless STACK_WIPE_SITES is redefined in rubysig.h
#
: ${CC:=gcc}
: ${CFLAGS:="-O2 -g -Wclobbered -fno-tree-dce -fno-stack-protector"}
: ${CXXFLAGS:=$CFLAGS}
for mod in mbarilib termios .; do
  [ -r $mod/Makefile ] && make -C $mod MINIRUBY=miniruby distclean
done
export CC CFLAGS CXXFLAGS
[ `which dpkg-architecture` ] && {
  rm -f ext/readline/libreadline.so*
  lib="/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`"
    #link Ruby readline extension with libreadline.5
  [ "$readline5" ] || readline5=$lib/libreadline.so.5
  if [ -r $readline5 ]; then
    ln -s $readline5 ext/readline/libreadline.so || exit $?
  else
    echo "WARNING:  Missing $readline5  (version 6 is incompatible)" >&2
    sleep 5
  fi

  #find the proper tcl support file in Debian's multiarch scheme
  tcfg=
  usr="/usr$lib"
  [ -r "$usr/tclConfig.sh" ] &&
    tcfg="--with-tclConfig-file=$usr/tclConfig.sh"
  [ -r "$usr/tkConfig.sh" ] &&
    tcfg="$tcfg --with-tkConfig-file=$usr/tkConfig.sh"
}
rm -f config.cache configure `find ext -name Makefile` &&
autoconf && exec configure --prefix=/opt/mbari \
  --enable-mbari-api --enable-pthread --disable-ucontext $tcfg $@
