#!/bin/bash
# configure ESP ruby 1.8.7p352 build for workstation -- 8/5/16 brent@mbari.org
# for gcc x86 add:
#  -fno-stack-protector
# to CFLAGS
# also note that gcc 4.7 is not compatible.  Use gcc 4.6 or lower.
: ${CFLAGS:="-O2 -g -fno-stack-protector"}
: ${CXXFLAGS:=$CFLAGS}
: ${CC:=gcc-4.6}
for mod in mbarilib termios .; do 
  [ -r $mod/Makefile ] && make -C $mod MINIRUBY=miniruby distclean
done
export CC CFLAGS CXXFLAGS
[ `which dpkg-architecture` ] && {
  arch="/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`"
  tcfg=
  [ -r "$arch/tclConfig.sh" ] &&
    tcfg="--with-tclConfig-file=$arch/tclConfig.sh"
  [ -r "$arch/tkConfig.sh" ] &&
    tcfg="$tcfg --with-tkConfig-file=$arch/tkConfig.sh"
}
rm -f config.cache configure `find ext -name Makefile` && 
autoconf && exec configure --prefix=/opt/mbari \
  --enable-mbari-api --enable-pthread --disable-ucontext $tcfg $@
