#!/bin/sh
# install ESP ruby 1.8.7p352 build for workstation -- 8/5/16 brent@mbari.org
# also install modules needed for ESP unless
#   coreOnly environment variable is set
#
make -j5 all || exit 3
sudo make install DESTDIR=$DESTDIR || exit 1
sudo chown $USER .installed.list || exit 2
  
[ -n "$coreOnly" ] || {
  echo "   Installing extensions required by MBARI ESP:"
  PATH=.:$PATH
  sudo rm -f termios/*.log termios/*.so
  buildUtils clean all &&
  echo "Installing MBARI extensions..."  &&
  sudo ./miniruby inst-mbari.rb $DESTDIR &&
  sudo ./buildUtils install &&
  sudo chown $USER termios/*.log termios/*.so
}

cd /opt/mbari/share/man/man1 &&
  sudo gzip *.1
